### ISSUE TITLE
draft-thomson-http-omnomnom

### ISSUE THREAD

**Issue by stash** [salesforce/tough-cookie#122]
Slated as part of 6265bis, [this draft](https://tools.ietf.org/html/draft-thomson-http-omnomnom) suggests:

>    Cookies that are set using insecure channels (i.e., HTTP over
>    cleartext TCP), MUST have a short time limit on the time that they
>    are persisted.  For instance, such cookies might only persist until
>    the user closes their browser.
> 
>    If a user agent detects a change in network conditions it SHOULD
>    remove any cookies that were established using insecure channels.

**Comment by colincasey** [comment]
the draft document referenced in this issue, EAT HTTP Cookies is no longer active and based on the following threads:
* [httpwg github issue](https://github.com/httpwg/http-extensions/issues/718)
* [chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=749059&q=draft-thomson-http-omnomnom-00&can=2)
* [browser status](https://www.chromestatus.com/feature/5658594150187008)

it doesn’t seem like any progress has been made to standardize this behavior.   since [6265bis](https://datatracker.ietf.org/doc/draft-ietf-httpbis-rfc6265bis/) no longer references the draft this issue will be closed.
