### ISSUE TITLE
Trailing slash breaks ESM compatibility

### ISSUE THREAD

**Issue by benmccann** [salesforce/tough-cookie#256]
Originally reported in https://github.com/sveltejs/kit/issues/7085

Loading this library in a project that uses Node.js ESM without bundling does not work:

> Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'node_modules/punycode/' is not supported resolving ES modules imported from build/server/chunks/_server.ts-7b9e82e7.js

I believe the error is coming from this line:

https://github.com/salesforce/tough-cookie/blob/d4ac5801dd2c2d53eec51329e5380bbffb23bfaf/lib/cookie.js#L32

Is there a reason to have that trailing slash or can it be removed?

**Comment by awaterma** [comment]
I think the slash isn't required; I'll take a look at our package.json.

**Comment by wjhsf** [comment]
This change was introduced in #238 in order to enforce the use of the [punycode npm package](https://www.npmjs.com/package/punycode), rather than [node's built-in](https://nodejs.org/api/punycode.html). One possible resolution is to import the main export directly, `require("punycode/punycode.js")`.
