### ISSUE TITLE
Cookies with lead '.' does not work properly

### ISSUE THREAD

**Issue by DNizovtsev** [salesforce/tough-cookie#26]
Looks problem in permuteDomain function:

var cookie = new TOUGH.Cookie({
    domain : '.google.com',
    path: '/',
    key : 'test01',
    value: 'value01'
});

var cookiejar = new TOUGH.CookieJar();
cookiejar.setCookie(cookie, 'http://www.google.com/', function () {
    cookiejar.getCookies('http://www.google.com',function (err, cookie) {
            console.log(cookie);
    });
});

output:
[]

**Comment by gebrits** [comment]
@DNizovtsev were you able to resolve this?
Having the exact same problem.

**Comment by JSBizon** [comment]
@gebrits No need use cookies with lead dots. Why do you use them?

**Comment by gebrits** [comment]
@JSBizon: indeed. Followed format for wildcard domains as given by chrome web developer plugin, which show leading dot. After removing the dot all works as expected.

**Comment by JSBizon** [comment]
@gebrits maybe chrome web developer plugin uses Netscape format file for store cookies.

**Comment by stash** [comment]
Sorry for the delayed response. I think what's happening is that the underlying `MemoryStore` doesn't use the canonicalized domain name to do its indexing. So, when getCookies looks there's nothing under "google.com".  This only happens for the above case where you construct the cookie instead of parsing it from a Set-Cookie string.

It's also true that the leading dot is completely unnecessary. All browsers ignore it and treat "example.com" and ".example.com" identically. Chrome adds it to the display to help people distinguish between host-only cookies (which omit the `Domain=` parameter from the `Set-Cookie` header).

I'm not really sure what the best way to fix this is. I could canonicalize the domain being input, but I know some use-cases of tough-cookie rely on that not happening.  I could perhaps add an option to `MemoryStore` to force canonicalization, but then other Store implementations wouldn't benefit.  Thoughts?

**Comment by JSBizon** [comment]
You may use my cookies store https://github.com/JSBizon/file-cookie-store for parsing these kind of files.

**Comment by Setitch** [comment]
.domain !== domain
http://stackoverflow.com/questions/1062963/how-do-browser-cookie-domains-work

Basically  dot in front of domain name makes restrictions and wildcards works for cookies.

I would be grateful for option that could set memorystorage for using or not this damn thing.

**Comment by stash-sfdc** [comment]
Worth noting is that the above stackoverflow question is from 2009. In my opinion, the world of cookies has moved on significantly since then and the answers are, at this time, more-or-less "stackovertrolls" (semi-factual or wrong, but with high-points). Modern browsers adhere closely to RFC6265, not RFC2965 ("Set-Cookie2") or any of the others. In RFC6265, and tough-cookie, .domain === domain. This bug is open because, by accident, there's a case where that assertion isn't true.

The work-around is to either manually remove the dot from the `domain` property of the Object being passed in, or to use the `Cookie.parse` function instead.

**Comment by moltar** [comment]
This caused me a day of pain!

My use case was reading cookies from a JSON file that was created by another process. That process (Puppeteer), which uses the dot notation by default.

E.g. Puppeteer cookie structure is the following:

```json
  {
    "name": "foo",
    "value": "bar",
    "domain": ".google.com",
    "path": "/",
    "expires": 2204567829.886289,
    "size": 59,
    "httpOnly": true,
    "secure": true,
    "session": false
  }
```

I was reading that JSON file manually and then converting it to a tough cookie's `Cookie` object by hand:

```ts
    const cookie = new Cookie({
       domain: myCookue.domain,
       // ...
    })
```

But that leading dot was causing all the cookies to drop.

**Comment by Nisthar** [comment]
@moltar so did you remove the dot from domain?

**Comment by moltar** [comment]
Yes remove leading dot

**Comment by Nisthar** [comment]
@moltar I have `www` missing from the domain for a cookie. I tried adding the domain manually.
But i can't set the cookie. It says "Cookie doesn't have www.domain.com as its host"

**Comment by Setitch** [comment]
New RFC specifies: 5.2.3.  The Domain Attribute how leading "." should be treated when used encountered also some browsers and other libraries had not obsoleted the old rfc yet and are still using it - wouldnt it be good for library to threat it easier for the user?

**Comment by ikv163** [comment]
Oh, Having the exact same problem.
