### ISSUE TITLE
Cookies with expiry time set to epoch zero are matched and not expired

### ISSUE THREAD

**Issue by faulpeltz** [salesforce/tough-cookie#455]
If the server sends a cookie with expiry time set to epoch zero (1970-01-01T00:00:00.000Z), the cookie is then returned in ``getCookies(url)`` even though "expire" is set to true (the default)

This is because ``expiryTime`` here should be checked for ``undefined`` not just ``!expiryTime``
https://github.com/salesforce/tough-cookie/blob/1a71340594beac95c4ea10fefe4eb79fdfead5c2/lib/cookie/cookieJar.ts#L940

**Comment by colincasey** [comment]
Thanks for the filing this issue @faulpeltz.

**Comment by domenic** [comment]
Hi! I'd like to gently request that a new version be released with this regression fix incorporated. It seems there have been a lot of meta-changes around dependencies, package publishing workflow, etc. since this was merged in September, but we still haven't seen an npm release with this fix.

For jsdom users, this is putting us between a rock and a hard place, where we can either use v4 which has deprecation warnings and working cookie deletion functionality, or v5 which has no deprecation warnings but broken cookie deletion abilities.

Of course, I understand very much that this is a spare-time project and you all are probably pretty busy. If you don't have time, I understand; I'm often that way with jsdom myself. But just in case it would make a difference, I wanted to drop a note letting you know how appreciated a new release would be.

Thanks!
