### ISSUE TITLE
`expiryDate` method missing in v5.0.0

### ISSUE THREAD

**Issue by wjhsf** [salesforce/tough-cookie#458]
The `expiryDate` method on the `Cookie` class was accidentally removed in the v5 release. It will be restored in the v5.0.1 release.

**Comment by colincasey** [comment]
I tracked this down to https://github.com/salesforce/tough-cookie/pull/289/commits/bae5ae80ca849a4eef1d866a97cc1736939036eb which was included in https://github.com/salesforce/tough-cookie/pull/289. Since this was included in a bundle of eslint-related changes I can only assume the method was flagged as unused because, otherwise, we should have seen unit test failures. It must have never had any coverage 😞
